# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the Python version to 3.7
python: 3.7

# Install the pip dependencies
install: pip install -r requirements.txt

script: echo "Success!"
